---
- hosts: dev
  become: True
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info

    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
    - name: Start the container
      docker_container:
        name: flamingo
        image: "thatz98/flamingo:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:3000:8080
    
