---
- hosts: dev
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: flamingo
        image: "thatz98/flamingo:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:3000:8080
    
