---
- hosts: all
  become: True
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Stop previous container
      docker_container:
        name: flamingo
        image: "thatz98/flamingo:{{PREV_DOCKER_TAG}}"
        state: stopped
    - name: Remove previous container
      docker_container:
        name: flamingo
        image: "thatz98/flamingo:{{PREV_DOCKER_TAG}}"
        state: absent
    - name: Start the container
      docker_container:
        name: flamingo
        image: "thatz98/flamingo:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:3000:3000
          - 0.0.0.0:8000:8000
    
